import React from 'react';

function Sucus(props) {
    return (
<div className="sucus">
    <div className="div1 suc reset" >2 </div>
    <div className="div2 suc rec1 reset">6</div>
    <div className="div3 suc reset"> 7</div>
    <div className="div4 suc reset"> 13</div>
    <div className="div5 suc reset"> 18</div>
    <div className="suc div6 reset"> 19</div>
    <div className="div7 suc reset"> 20</div>
    <div className="div8 suc reset"> 22</div>
    <div className="div9 suc reset"> 24</div>
    <div className="div10 suc reset">25 </div>
    <div className="div11 suc reset">26 </div>
    <div className="div12 suc reset">35 </div>
    <div className="div13 suc reset"> 37</div>
    <div className="div14 suc reset"> 38</div>
    <div className="div15 suc reset"> 39</div>
    <div className="div16 suc reset"> 40</div>
    <div className="div17 suc reset"> 41</div>
    <div className="div18 suc reset"> 42</div>
    <div className="div19 suc reset"> 43</div>
    <div className="div20 suc reset"> 44</div>
    <div className="div21 suc reset"> 45</div>
    <div className="div22 suc reset"> 46</div>
    <div className="div23 suc reset"> 47</div>
    <div className="div24 suc reset"> 48</div>
    <div className="div25 suc reset"> 49</div>
    <div className="div26 suc reset"> 51</div>
    <div className="div27 suc reset"> 52</div>
    <div className="div28 suc reset"> 53</div>
    <div className="div29 suc reset"> 55</div>
    <div className="div30 suc reset"> 56</div>
    <div className="div31 suc reset"> 57</div>
    <div className="div32 suc reset"> 58</div>
    <div className="div33 suc reset"> 59</div>
    <div className="div34 suc reset"> 60</div>
    <div className="div35 suc reset"> 61</div>
    <div className="div36 suc rec1"> 63</div>
    <div className="div37 suc reset"> 64</div>
    <div className="div38 suc reset"> 65</div>
    <div className="div39 suc reset"> 66</div>
    <div className="div40 suc reset"> 67</div>
    <div className="div41 suc reset"> 68</div>
    <div className="div42 suc reset"> 69</div>
    <div className="div43 suc reset"> 70</div>
    <div className="div44 suc reset"> 71</div>
    <div className="div45 suc reset"> 74</div>
    <div className="div46 suc rec1 reset"> 75</div>
    <div className="div47 suc reset"> 78</div>
    <div className="div48 suc reset"> 80</div>
    <div className="div49 suc reset"> 82</div>
    <div className="div50 suc reset"> 83</div>
    <div className="div51 suc reset"> 84</div>
    <div className="div52 suc reset"> 85</div>
    <div className="div53 suc rec1 reset"> 88</div>
    <div className="div54 suc reset"> 90</div>
    <div className="div55 suc reset"> 91</div>
    <div className="div56 suc reset"> 92</div>
    <div className="div57 suc reset"> 93</div>
    <div className="div58 suc reset"> 94</div>
    <div className="div59 suc reset"> 95</div>
    <div className="div60 suc reset"> 96</div>
    <div className="div61 suc reset"> 97</div>
    <div className="div62 suc reset"> 99</div>
    <div className="div63 suc reset"> 101</div>
    <div className="div64 suc reset"> 103</div>
    <div className="div65 suc reset"> 104</div>
    <div className="div66 suc reset"> 105</div>
    <div className="div67 suc rec1 reset"> 107</div>
    <div className="div68 suc reset"> 108</div>
    <div className="div69 suc reset"> 109</div>
    <div className="div70 suc reset"> 110</div>
    <div className="div71 suc reset"> 111</div>
    <div className="div72 suc reset"> 118</div>
    <div className="div73 suc reset"> 121</div>
    <div className="div74 suc reset"> 123</div>
    <div className="div75 suc reset"> 124</div>
    <div className="div76 suc reset"> 125</div>
    <div className="div77 suc reset"> 126</div>
    <div className="div78 suc reset"> 129</div>
    <div className="div79 suc reset"> 130</div>
    <div className="div80 suc reset"> 131</div>
    <div className="div81 suc reset"> 136</div>
    <div className="div82 suc reset"> 142</div>
    <div className="div83 suc reset"> 149</div>
    <div className="div84 suc reset"> 151</div>
    <div className="div85 suc reset"> 153</div>
    <div className="div86 suc reset"> 154</div>
    <div className="div87 suc reset"> 155</div>
    <div className="div88 suc reset"> 158</div>
    <div className="div89 suc reset"> 159</div>
    <div className="div90 suc reset"> 160</div>
    <div className="div91 suc reset"> 161</div>
    <div className="div92 suc reset"> 162</div>
    <div className="div93 suc reset"> 163</div>
    <div className="div94 suc reset"> 164</div>
    <div className="div95 suc reset"> 165</div>
    <div className="div96 suc reset"> 167</div>
    <div className="div97 suc reset"> 168</div>
    <div className="div98 suc reset"> 170</div>
    <div className="div99 suc rec1 reset"> 171</div>
    <div className="div100 suc reset">174 </div>
    <div className="div101 suc reset"> 175</div>
    <div className="div102 suc reset"> 176</div>
    <div className="div103 suc reset"> 178</div>
    <div className="div104 suc reset"> 179</div>
    <div className="div105 suc reset"> 180</div>
    <div className="div106 suc reset"> 181</div>
    <div className="div107 suc rec1 reset"> 183</div>
    <div className="div108 suc reset"> 184</div>
    <div className="div109 suc reset"> 185</div>
    <div className="div110 suc rec1 reset"> 186</div>
    <div className="div111 suc reset"> 188</div>
    <div className="div112 suc reset"> 189</div>
    <div className="div113 suc reset"> 192</div>
    <div className="div114 suc reset"> 196</div>
    <div className="div115 suc reset"> 197</div>
    <div className="div116 suc reset"> 199</div>
    <div className="div117 suc reset"> 203</div>
    <div className="div118 suc reset"> 204</div>
    <div className="div119 suc reset"> 208</div>
    <div className="div120 suc reset"> 209</div>
    <div className="div121 suc reset"> 215</div>
    <div className="div122 suc reset"> 219</div>
    <div className="div123 suc reset"> 220</div>
    <div className="div124 suc reset"> 235</div>
</div>
    );
}

export default Sucus;